### ISSUE TITLE
似乎会因为微信使用mmtls而抓不到包？

### ISSUE THREAD

**Issue by aurantiaco-sucus** [Gomorebug/auto-jdsd#1]
我之前一直遇到个问题：我个人的（Linux PC）上的虚拟机或者双系统上运行的auto-jdsd都卡在了“请在1分钟内启动已登录的经典诵读”的环节，但是在舍友的PC上（用我的号）却一切正常。

尝试手动在Windows 11上使用mitmproxy（web）抓包，并未发现域名中含有“jdsd”的https包，只有铺天盖地的“mmtls”。我对此了解不深，只从网上的些许资料得知mmtls似乎是tx规避网络问题的一直“代理”手段，小程序对jdsd服务器的访问大略是被“代理”进去了？

经过一些研究，发现使用proxifier全局代理+fiddler classic+proxifier拦截所有“szshort"请求（szshort.weixin.qq.com; szextshort.weixin.qq.com; szminorshort.weixin.qq.com）之后（启动微信）就有机会见到jdsd的请求（并使用1.0版本工具）了。

不知这个问题可否在同志的项目解决？

**Comment by BitSim** [comment]
由于本人不会Linux系统，所以没做过Linux系统上的测试（）。
事实上我之前也遇到了“mmtls”的问题，但后续的过程发现中发现是“相关证书”没有安装。如果你在windows系统上使用2.0.0版本卡在经典诵读环节，可以在”管理用户证书“->"受信任的根证书颁发机构”检查有没有mitmproxy证书。如果没有，可以在此运行本程序进行检查。如果以上方法仍是不行，请检查"C:\Users\你的用户名"文件中存不存在“.mitmproxy”文件夹，如有，请在里面安装证书。
如果还是不能解决您的问题，我将在后续中进行完善，感谢您的支持以及对代码的研究！！！
