### ISSUE TITLE
最近几天开始无法使用

### ISSUE THREAD

**Issue by JJQ1631** [Gomorebug/auto-jdsd#2]
![image](https://github.com/Gomorebug/GZHU-AUTO-JDSD/assets/114285785/f2b51a24-1514-4145-a7a0-581b8094e04e)

**Comment by JJQ1631** [comment]
突然说要登录小程序获取key值，之前都不用的。然后获取完之后就不行了

**Comment by JJQ1631** [comment]
![a14495d088c6aadcff3e6d7132d4254](https://github.com/Gomorebug/GZHU-AUTO-JDSD/assets/114285785/adc9e636-b1f2-4aa3-b176-83b9241ce1e9)

**Comment by BitSim** [comment]
> 

首先感谢使用本软件。
这种问题应该是所有人都用不了经典诵读，这属于小程序后端的问题，之前一学期发生过几次。所以不属于本软件的错误。
对于该情况可以隔段时间再来使用👍
最后提醒一下可以把图片放文字一起提问，还有如果身边有人使用本软件觉得好用的话可以给本项目点个star哈🌟

**Comment by JJQ1631** [comment]
![image](https://github.com/Gomorebug/GZHU-AUTO-JDSD/assets/114285785/e0734991-7dc6-43bf-acbb-9b5c5e4c4f92)
最近一直这样，持续好久了，有没有什么解决办法？手机这边无法登录，电脑那里就操作不了。

**Comment by BitSim** [comment]
> ![image](https://user-images.githubusercontent.com/114285785/245004653-e0734991-7dc6-43bf-acbb-9b5c5e4c4f92.png) 最近一直这样，持续好久了，有没有什么解决办法？手机这边无法登录，电脑那里就操作不了。

不用发图片了，我知道你的情况，这种情况下大家都没办法用，你可以去问问身边的同学或者学长，每年小程序就是有很长一段时间没法用的你要习惯

**Comment by BitSim** [comment]
> 突然说要登录小程序获取key值，之前都不用的。然后获取完之后就不行了

如果没有其他问题我要关闭这个issue了
